io.dropwizard.metrics:metrics-core = 4.2.38
com.google.guava:guava = 33.6.0-jre
com.palantir.safe-logging:* = 3.15.0
com.palantir.tracing:* = 6.34.0
com.palantir.tritium:* = 0.129.0

# test dependencies
net.jqwik:* = 1.9.3
org.assertj:assertj-core = 3.27.7
org.junit.jupiter:* = 6.0.3
org.junit.platform:* = 6.0.3
