io.dropwizard.metrics:metrics-core = 4.2.39
com.google.guava:guava = 33.6.0-jre
com.palantir.safe-logging:* = 3.16.0
com.palantir.tracing:* = 6.36.0
com.palantir.tritium:* = 0.131.0

# test dependencies
org.quicktheories:quicktheories = 0.26
org.assertj:assertj-core = 3.27.7
org.junit.jupiter:* = 6.1.1
org.junit.platform:* = 6.1.0
